[workspace]
members = [
 "storage",
 "fin_db",
 "mem_db",
 "temp_db",
]
resolver = "2"

[patch."https://github.com/FindoraNetwork/fmerk.git"]
fmerk = { git = "https://github.com/ktmlm/fmerk", branch = "master"}
